import { RecipeForm } from '@/components/recipe-form';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Sparkles } from 'lucide-react';
import { Suspense } from 'react';

type NewRecipePageProps = {
  searchParams?: {
    title?: string;
    ingredients?: string;
    instructions?: string;
    tags?: string;
    fromAI?: string;
  }
}

function GeneratedRecipeBanner() {
  return (
    <div className="mb-6 rounded-lg border border-blue-500/50 bg-blue-500/10 p-4 text-center">
        <div className="flex items-center justify-center gap-2">
            <Sparkles className="h-5 w-5 text-blue-400" />
            <p className="text-sm font-medium text-blue-300">
            This recipe was generated by AI. Please review and adjust as needed before saving.
            </p>
        </div>
    </div>
  )
}

export default function NewRecipePage({ searchParams }: NewRecipePageProps) {

  const recipeFromAI = searchParams?.fromAI === 'true' ? {
    title: searchParams?.title || '',
    ingredients: searchParams?.ingredients || '',
    instructions: searchParams?.instructions || '',
    tags: searchParams?.tags || '',
  } : undefined;

  return (
    <div className="container mx-auto max-w-2xl py-8">
      <Card>
        <CardHeader>
          <div className="flex items-start justify-between">
            <div>
              <CardTitle className="text-3xl font-headline">Add a New Recipe</CardTitle>
              <CardDescription>Share a delicious creation with the family.</CardDescription>
            </div>
            <Button asChild variant="outline">
              <Link href="/recipes/generate">
                <Sparkles className="mr-2 h-4 w-4" />
                Generate with AI
              </Link>
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <Suspense fallback={null}>
            {recipeFromAI && <GeneratedRecipeBanner />}
          </Suspense>
          <RecipeForm recipe={recipeFromAI} />
        </CardContent>
      </Card>
    </div>
  );
}
