name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: "file:./test.db"

      - name: Run database setup
        run: |
          npx prisma migrate reset --force --skip-seed
          npx prisma db push
        env:
          DATABASE_URL: "file:./test.db"

      - name: Run TypeScript type checking
        run: npm run typecheck

      - name: Run ESLint
        run: npm run lint

      - name: Check code formatting
        run: npm run format:check

      - name: Build application
        run: npm run build
        env:
          # Skip telemetry during CI
          NEXT_TELEMETRY_DISABLED: 1
          # Database URL for build
          DATABASE_URL: "file:./test.db"
          # Dummy auth secret for build
          NEXTAUTH_SECRET: "test-secret-for-ci"
          NEXTAUTH_URL: "http://localhost:3000"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-files
          path: |
            .next/
            !.next/cache/
          retention-days: 1